In [3]:
import numpy as np

In [2]:
# working with shape attribute
# 

In [ ]:
# 1 D array []

In [5]:
arr1 = np.array(np.arange(5,10))
arr1

array([5, 6, 7, 8, 9])

In [26]:
arr1.shape

(5,)

In [27]:
arr1.ndim

1

In [ ]:
# 2 d array [ [] ]

In [29]:
arr1_1 = np.array([np.arange(1,6)])
arr1_1

array([[1, 2, 3, 4, 5]])

In [30]:
arr1_1.shape

(1, 5)

In [31]:
arr1_1.ndim

2

In [15]:
# arr2 = np.array([[np.arange(0,10,2)],[np.arange(10,20,2)]])
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
arr2.shape

(2, 5)

In [28]:
arr2.ndim

2

In [ ]:
# 3 dimentional

In [22]:
arr3 = np.array([ [[1,2],[2,3]], [[1,4],[4,6]] ])
arr3

array([[[1, 2],
        [2, 3]],

       [[1, 4],
        [4, 6]]])

In [24]:
arr3.shape

(2, 2, 2)

In [ ]:
# ndim evaluate number of dimension

In [25]:
arr3.ndim

3

In [33]:
# size : number of element

In [35]:
arr3.size

8

In [36]:
arr2.size

10

In [37]:
# itemsize: like int 4 byte, float 8 byte

In [45]:
arr4 = np.linspace(2,5,10)
arr4

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [48]:
arr4.itemsize

8

In [49]:
arr1.itemsize

8

In [52]:
arr3.itemsize

8

In [53]:
x = np.array([1,2,3], dtype = np.int32)
x.itemsize

4

In [54]:
# dtype : data type

In [56]:
arr1.dtype

dtype('int64')

In [58]:
arr1_1.dtype

dtype('int64')

In [59]:
arr2.dtype

dtype('int64')

In [60]:
arr3.dtype

dtype('float64')

In [61]:
arr4.dtype

dtype('float64')

In [62]:
# astype('data_type_name'): similar to type conversion

In [64]:
arr3.astype('float')

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [65]:
arr3.astype('int')

array([2, 2, 2, 3, 3, 3, 4, 4, 4, 5])

In [66]:
arr3.astype('str')

array(['2.0', '2.3333333333333335', '2.6666666666666665', '3.0',
       '3.333333333333333', '3.6666666666666665', '4.0',
       '4.333333333333333', '4.666666666666666', '5.0'], dtype='<U32')