In [16]:
import numpy as np

In [17]:
# reshape(row,col): 
# note: must follow total_element = row*col
# example: total_element = 24
# .reshape(2*12) or 3*4, 4*6, 12*2, 12*1, 6*4

In [18]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
b = np.copy(a).reshape(4,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [20]:
c = np.arange(24).reshape(6,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# Slicing Start from here

In [ ]:
# Extract column 3

In [21]:
c[range(6),2]

array([ 2,  6, 10, 14, 18, 22])

In [23]:
c[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [24]:
# Extract : 
# 13 14
# 17 18

In [28]:
c[3:5, 1:3]

array([[13, 14],
       [17, 18]])

In [30]:
# Explanation
# c[row -> start: stop 1 step before ,  col -> start: stop 1 step before]

In [31]:
# Extract : 
# 14 15
# 18 19
# 22 23

In [34]:
c[3:6 , 2:4]

array([[14, 15],
       [18, 19],
       [22, 23]])

In [36]:
c[3: , 2:]

array([[14, 15],
       [18, 19],
       [22, 23]])

In [39]:
# Iteration like for loop

In [41]:
for row in c:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [42]:
# built in iteration function

In [43]:
for item in np.nditer(c):
    print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
