In [2]:
import numpy as np

In [3]:
a = np.arange(1,7)
b = np.arange(4,10)
print("a:",a)
print("b:",b)

a: [1 2 3 4 5 6]
b: [4 5 6 7 8 9]


In [ ]:
# basic operations

In [4]:
# addition: element wise addition

In [5]:
a + b

array([ 5,  7,  9, 11, 13, 15])

In [6]:
# subtraction: element wise subtraction

In [7]:
a - b

array([-3, -3, -3, -3, -3, -3])

In [8]:
# multiplication: element wise multiplication : similar to vector multiplication

In [9]:
a * b

array([ 4, 10, 18, 28, 40, 54])

In [10]:
# division: element wise division

In [11]:
a / b

array([0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
       0.66666667])

In [12]:
# scalar multiplication

In [13]:
a*2

array([ 2,  4,  6,  8, 10, 12])

In [14]:
# checking condition true or false

In [15]:
b > 3

array([ True,  True,  True,  True,  True,  True])

In [16]:
# matrix multiplication or dot multiplication   
# m matrix row X n matrix col 
# (Mr X Mc), (Nr x Nc)
# mul. of (M.N) possible if Mc = Nr other then not :new dimension = Mr X Nc 
# mul. of (N.M) possible if Nc = Mr other then not :new dimension = Mr X Nc 


In [17]:
m1 = np.arange(6).reshape(2,3)
m2 = np.arange(6,12).reshape(3,2)

m1.dot(m2)

array([[ 28,  31],
       [100, 112]])

In [18]:
m2.dot(m1)

array([[21, 34, 47],
       [27, 44, 61],
       [33, 54, 75]])

In [ ]:
# unary operations

In [19]:
# Min, Max of a matrix

In [20]:
m1.min()

np.int64(0)

In [21]:
m2.min()
print(m2.min())

6


In [22]:
print(m1.max())
print(m2.max())

5
11


In [44]:
m1.sum()

np.int64(15)

In [23]:
# axis wise or row wise max min value

In [ ]:
m3 = np.array([[1,9,6,8,5],
               [2,5,7,6,12],
               [0,82,4,65,3]])

In [ ]:
# axis = 0 : mean each column wise operation

In [37]:
m3.min(axis=0)

array([0, 5, 4, 6, 3])

In [42]:
m3.max(axis=0)

array([ 2, 82,  7, 65, 12])

In [41]:
m3.sum(axis=0)

array([ 3, 96, 17, 79, 20])

In [ ]:
# axis = 1 : mean each row wise operation

In [39]:
m3.min(axis=1)

array([1, 2, 0])

In [43]:
m3.max(axis=1)

array([ 9, 12, 82])

In [40]:
m3.sum(axis=1)

array([ 29,  32, 154])

In [46]:
m3.mean()

np.float64(14.333333333333334)

In [ ]:
# universal functions

In [ ]:
# standard deviation

In [47]:
m3.std()

np.float64(23.604142762565125)

In [48]:
# median 

In [49]:
np.median(m3)

np.float64(6.0)

In [50]:
# sin

In [51]:
np.sin(m3)

array([[ 0.84147098,  0.41211849, -0.2794155 ,  0.98935825, -0.95892427],
       [ 0.90929743, -0.95892427,  0.6569866 , -0.2794155 , -0.53657292],
       [ 0.        ,  0.31322878, -0.7568025 ,  0.82682868,  0.14112001]])

In [52]:
# exponent

In [53]:
np.exp(m3)

array([[2.71828183e+00, 8.10308393e+03, 4.03428793e+02, 2.98095799e+03,
        1.48413159e+02],
       [7.38905610e+00, 1.48413159e+02, 1.09663316e+03, 4.03428793e+02,
        1.62754791e+05],
       [1.00000000e+00, 4.09399696e+35, 5.45981500e+01, 1.69488924e+28,
        2.00855369e+01]])

In [57]:
ct = np.sqrt(m3)
ct

array([[1.        , 3.        , 2.44948974, 2.82842712, 2.23606798],
       [1.41421356, 2.23606798, 2.64575131, 2.44948974, 3.46410162],
       [0.        , 9.05538514, 2.        , 8.06225775, 1.73205081]])

In [ ]:
# converting data type using astype()

In [58]:
ct.astype(int)

array([[1, 3, 2, 2, 2],
       [1, 2, 2, 2, 3],
       [0, 9, 2, 8, 1]])