In [27]:
import numpy as np

In [28]:
a = np.arange(6,12).reshape(3,2)
a

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [29]:
a.ndim

2

In [30]:
# if we want to reshape multi-dimensional arrays to 1D
# we use ravel function
# without loosing any thing

In [31]:
a.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [32]:
# similar to matrix transpose : row --> col , col --> row

In [33]:
a.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [ ]:
# stacking: 
# hstack : make horizontally stack or merge them
# vstack : make vertically stack or merge them

In [37]:
a

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [35]:
b = np.arange(12,18).reshape(3,2)
b

array([[12, 13],
       [14, 15],
       [16, 17]])

In [36]:
np.hstack((a,b))

array([[ 6,  7, 12, 13],
       [ 8,  9, 14, 15],
       [10, 11, 16, 17]])

In [38]:
np.vstack((a,b))

array([[ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [39]:
# splitting 

In [40]:
a

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
# horizontal split
# we can split horizontally at most the num. of col. we have
# not more than

In [47]:
np.hsplit(a,2)

[array([[ 6],
        [ 8],
        [10]]),
 array([[ 7],
        [ 9],
        [11]])]

In [50]:
# vertical split 

In [51]:
np.vsplit(a,3)

[array([[6, 7]]), array([[8, 9]]), array([[10, 11]])]