In [1]:
import numpy as np

In [2]:
arr = np.random.randint(low=1, high=100, size=20).reshape(4,5)
arr

array([[80, 27, 85,  8, 78],
       [55,  1,  2, 42, 18],
       [49, 89,  2, 62, 44],
       [ 7, 32, 56, 60, 27]])

In [3]:
arr[0]

array([80, 27, 85,  8, 78])

In [4]:
arr>50

array([[ True, False,  True, False,  True],
       [ True, False, False, False, False],
       [False,  True, False,  True, False],
       [False, False,  True,  True, False]])

In [5]:
(arr>50).shape

(4, 5)

In [6]:
# indexing using boolean arrays
arr[arr>50]

array([80, 85, 78, 55, 89, 62, 56, 60])

In [ ]:
# i want array which contains element larger than 50 and odd num
# must use bitwise & : boolean & boolean
arr[(arr>50) & (arr%2 != 0)]

array([85, 55, 89])

In [ ]:
# i want array which contains element larger than 50 or odd num
# must use bitwise | : boolean | boolean
arr[(arr>50) | (arr%2 != 0)]

array([80, 27, 85, 78, 55,  1, 49, 89, 62,  7, 56, 60, 27])

In [20]:
# i that case i want to replace those values using 0
arr[(arr>50) & (arr%2 != 0)] = 0
arr

array([[80, 27,  0,  8, 78],
       [ 0,  1,  2, 42, 18],
       [49,  0,  2, 62, 44],
       [ 7, 32, 56, 60, 27]])